seed: 0
exp_name: td3_epoch_1200_obs_type_0
policy: td3
timeout_steps: 80
data_dir: carla_cost_20
episode_rerun_num: 100
sample_episode_num: 20
evaluate_episode_num: 1
pretrain_dir: data/carla_cost_20/td3_epoch_1200_obs_type_0/td3_epoch_1200_obs_type_0_s0/
continue_from_epoch: 175
obs_type: 0
td3:
    num_qc: 1
    cost_limit: 20
    use_cost_decay: false
    cost_start: 100
    cost_end: 5
    decay_epoch: 200
    KP: 0.1
    KI: 0.003
    KD: 0.001
    steps_per_epoch: 2000
    actor_lr: 0.001
    critic_lr: 0.001
    ac_model: mlp
    hidden_sizes:
    - 256
    - 256
    act_noise: 0.1
    target_noise: 0.2
    noise_clip: 0.5
    policy_delay: 2
    gamma: 0.99
    polyak: 0.995
    num_q: 2
    worker_config:
        warmup_steps: 600
        batch_size: 100
        buffer_size: 20000
