policy_type: 'text_to_scene'
scenario_category: 'planning'

route_dir: 'safebench/scenario/scenario_data/route'
scenic_dir: 'safebench/scenario/scenario_data/scenic_data/'
sample_num: 50
opt_step: 10
select_num: 2

method: 'text_to_scene'
scenario_id: null
route_id: [4,5,6,7,8,9,10,11,12,13]

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 1.0

use_cache: true
cache_dir: 'graph_cache'